import 'reflect-metadata';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import {
  Usuario,
  Genero,
  Contenido,
  ContenidoReport,
  ModeracionLog,
  Rating,
  Review,
  ReviewVersion,
  ReviewReport,
  UserReport,
  ReviewVoto,
  ReviewRespuesta,
  Favorito,
  ListaItem,
  Notificacion,
  Seguimiento,
  ListaPersonalizada,
  ListaPersonalizadaContenido,
  PasswordResetToken,
  EmailVerificationToken,
  Sesion,
  TwoFactorSecret,
  Personaje,
  VoiceActor,
  ContenidoPersonaje,
  PersonajeVoiceActor,
  OAuthAccount,
  FavoritoPersonaje,
  PushSubscription,
} from './entities';

dotenv.config();

export const AppDataSource = new DataSource({
  type: 'mssql',
  host: process.env.DB_HOST ?? 'localhost',
  port: parseInt(process.env.DB_PORT ?? '1433'),
  username: process.env.DB_USER ?? 'sa',
  password: process.env.DB_PASS ?? '',
  database: process.env.DB_NAME ?? 'AniRate',
  entities: [
    Usuario,
    Genero,
    Contenido,
    ContenidoReport,
    ModeracionLog,
    Rating,
    Review,
    ReviewVersion,
    ReviewReport,
    UserReport,
    ReviewVoto,
    ReviewRespuesta,
    Favorito,
    ListaItem,
    Notificacion,
    Seguimiento,
    ListaPersonalizada,
    ListaPersonalizadaContenido,
    PasswordResetToken,
    EmailVerificationToken,
    Sesion,
    TwoFactorSecret,
    Personaje,
    VoiceActor,
    ContenidoPersonaje,
    PersonajeVoiceActor,
    OAuthAccount,
    FavoritoPersonaje,
    PushSubscription,
  ],
  migrations: ['src/database/migrations/*.ts'],
  migrationsTableName: 'migrations',
  options: {
    trustServerCertificate: true,
    encrypt: false,
  },
  pool: {
    max: parseInt(process.env.DB_POOL_MAX ?? '10'),
    min: parseInt(process.env.DB_POOL_MIN ?? '2'),
    idleTimeoutMillis: 30000,
  },
});
